apiVersion: v1
kind: Service
metadata:
  name: nfs
spec:
  selector:
    group: nfs
  clusterIP: None
  ports:
  - name: portmapper
    port: 111
    targetPort: portmapper
  - name: nfs
    port: 2049
    targetPort: nfs
  - name: mountd
    port: 42069
    targetPort: mountd
  - name: statd-in
    port: 42070
    targetPort: statd-in
  - name: statd-out
    port: 42071
    targetPort: statd-out
  - name: statd-nlm
    port: 42072
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  labels:
    name: nfs-server
    group: nfs
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nfs-server
  template:
    metadata:
      name: nfs-server
      labels:
        name: nfs-server
        group: nfs
    spec:
      hostname: server
      subdomain: nfs
      containers:
      - image: richiejp/suse-scapy:latest
        imagePullPolicy: Always
        name: server
        securityContext:
          privileged: true
          procMount: Unmasked
          seccompProfile:
            type: Unconfined
        ports:
        - name: nfs
          containerPort: 2049
        - name: mountd
          containerPort: 42069
        - name: statd-in
          containerPort: 42070
        - name: statd-out
          containerPort: 42071
        - name: statd-nlm
          containerPort: 42072
        volumeMounts:
        - mountPath: /data
          name: nfs-server
        - mountPath: /sys
          name: sys
        command:
        - /usr/bin/nfs-server.sh
        args:
        - /data/nfs4
        - /data/nfs3
        stdin: true
        tty: true
      volumes:
      - name: nfs-server
        persistentVolumeClaim:
          claimName: nfs-server
      - name: sys
        hostPath:
          path: /sys
          type: Directory
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scapy-repl
  labels:
    name: scapy-repl
    group: nfs
spec:
  replicas: 1
  selector:
    matchLabels:
      name: scapy-repl
  template:
    metadata:
      name: scapy-repl
      labels:
        name: scapy-repl
        group: nfs
    spec:
      hostname: scapy-repl
      subdomain: nfs
      containers:
      - image: richiejp/suse-scapy:latest
        imagePullPolicy: Always
        name: scapy-repl
        securityContext:
          privileged: true
          procMount: Unmasked
          seccompProfile:
            type: Unconfined
        command:
        - /usr/bin/nfs-client.sh
        args:
        - /data/nfs4
        - /data/nfs3
        stdin: true
        tty: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpftrace
  labels:
    name: bpftrace
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bpftrace
  template:
    metadata:
      name: bpftrace
      labels:
        name: bpftrace
    spec:
      hostname: bpftrace
      subdomain: debug
      hostNetwork: true
      hostPID: true
      hostIPC: true
      volumes:
      - name: sys
        hostPath:
          path: /sys
          type: Directory
      containers:
      - image: quay.io/iovisor/bpftrace:latest
        name: bpftrace
        securityContext:
          privileged: true
          procMount: Unmasked
          seccompProfile:
            type: Unconfined
        command:
        - bash
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /sys
          name: sys

